// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_article.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addArticleTag = `-- name: AddArticleTag :exec
INSERT INTO article_tags (article_id, tag_id) VALUES (?, ?)
`

type AddArticleTagParams struct {
	ArticleID uint64
	TagID     uint64
}

func (q *Queries) AddArticleTag(ctx context.Context, arg AddArticleTagParams) error {
	_, err := q.db.ExecContext(ctx, addArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const adminCountArticles = `-- name: AdminCountArticles :one
SELECT COUNT(*)
FROM articles a
WHERE (? IS NULL OR a.status = ?)
  AND (? IS NULL OR a.title LIKE ?)
  AND (? IS NULL OR a.category_id = ?)
  AND (? IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at WHERE at.article_id = a.id AND at.tag_id = ?))
`

type AdminCountArticlesParams struct {
	Status     NullArticlesStatus
	Keyword    sql.NullString
	CategoryID sql.NullInt64
	TagID      sql.NullInt64
}

func (q *Queries) AdminCountArticles(ctx context.Context, arg AdminCountArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountArticles,
		arg.Status,
		arg.Status,
		arg.Keyword,
		arg.Keyword,
		arg.CategoryID,
		arg.CategoryID,
		arg.TagID,
		arg.TagID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetArticle = `-- name: AdminGetArticle :one
SELECT a.id, a.title, a.content, a.status, a.published_at, a.created_at, a.updated_at,
       a.category_id, c.name AS category_name
FROM articles a
LEFT JOIN categories c ON c.id = a.category_id
WHERE a.id = ?
`

type AdminGetArticleRow struct {
	ID           uint64
	Title        string
	Content      string
	Status       ArticlesStatus
	PublishedAt  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CategoryID   sql.NullInt64
	CategoryName sql.NullString
}

func (q *Queries) AdminGetArticle(ctx context.Context, id uint64) (AdminGetArticleRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetArticle, id)
	var i AdminGetArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
	)
	return i, err
}

const adminListArticles = `-- name: AdminListArticles :many
SELECT a.id, a.title, a.content, a.status, a.published_at, a.created_at, a.updated_at,
       a.category_id, c.name AS category_name
FROM articles a
LEFT JOIN categories c ON c.id = a.category_id
WHERE (? IS NULL OR a.status = ?)
  AND (? IS NULL OR a.title LIKE ?)
  AND (? IS NULL OR a.category_id = ?)
  AND (? IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at WHERE at.article_id = a.id AND at.tag_id = ?))
ORDER BY a.published_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type AdminListArticlesParams struct {
	Status     NullArticlesStatus
	Keyword    sql.NullString
	CategoryID sql.NullInt64
	TagID      sql.NullInt64
	Limit      int32
	Offset     int32
}

type AdminListArticlesRow struct {
	ID           uint64
	Title        string
	Content      string
	Status       ArticlesStatus
	PublishedAt  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CategoryID   sql.NullInt64
	CategoryName sql.NullString
}

func (q *Queries) AdminListArticles(ctx context.Context, arg AdminListArticlesParams) ([]AdminListArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListArticles,
		arg.Status,
		arg.Status,
		arg.Keyword,
		arg.Keyword,
		arg.CategoryID,
		arg.CategoryID,
		arg.TagID,
		arg.TagID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListArticlesRow{}
	for rows.Next() {
		var i AdminListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const articleExists = `-- name: ArticleExists :one
SELECT COUNT(*) FROM articles WHERE id = ?
`

func (q *Queries) ArticleExists(ctx context.Context, id uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, articleExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :execresult
INSERT INTO articles (title, content, category_id, status, published_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateArticleParams struct {
	Title       string
	Content     string
	CategoryID  sql.NullInt64
	Status      ArticlesStatus
	PublishedAt time.Time
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createArticle,
		arg.Title,
		arg.Content,
		arg.CategoryID,
		arg.Status,
		arg.PublishedAt,
	)
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE id = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteArticleTags = `-- name: DeleteArticleTags :exec
DELETE FROM article_tags WHERE article_id = ?
`

func (q *Queries) DeleteArticleTags(ctx context.Context, articleID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTags, articleID)
	return err
}

const updateArticle = `-- name: UpdateArticle :execrows
UPDATE articles
SET title = ?, content = ?, category_id = ?, status = ?, published_at = ?
WHERE id = ?
`

type UpdateArticleParams struct {
	Title       string
	Content     string
	CategoryID  sql.NullInt64
	Status      ArticlesStatus
	PublishedAt time.Time
	ID          uint64
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Content,
		arg.CategoryID,
		arg.Status,
		arg.PublishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
