// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_content.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const adminCountComments = `-- name: AdminCountComments :one
SELECT COUNT(*) FROM comments
`

func (q *Queries) AdminCountComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListComments = `-- name: AdminListComments :many
SELECT cm.id, cm.article_id, cm.parent_id, cm.nickname, cm.email, cm.website, cm.avatar,
       cm.content, cm.is_admin, cm.ip, cm.created_at,
       a.title AS article_title
FROM comments cm
LEFT JOIN articles a ON a.id = cm.article_id
ORDER BY cm.created_at DESC, cm.id DESC
LIMIT ? OFFSET ?
`

type AdminListCommentsParams struct {
	Limit  int32
	Offset int32
}

type AdminListCommentsRow struct {
	ID           uint64
	ArticleID    sql.NullInt64
	ParentID     sql.NullInt64
	Nickname     string
	Email        string
	Website      string
	Avatar       string
	Content      string
	IsAdmin      bool
	Ip           string
	CreatedAt    time.Time
	ArticleTitle sql.NullString
}

func (q *Queries) AdminListComments(ctx context.Context, arg AdminListCommentsParams) ([]AdminListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListCommentsRow{}
	for rows.Next() {
		var i AdminListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ParentID,
			&i.Nickname,
			&i.Email,
			&i.Website,
			&i.Avatar,
			&i.Content,
			&i.IsAdmin,
			&i.Ip,
			&i.CreatedAt,
			&i.ArticleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminStats = `-- name: AdminStats :one
SELECT
  (SELECT COUNT(*) FROM articles WHERE status = 'published') AS published_count,
  (SELECT COUNT(*) FROM articles WHERE status = 'draft') AS draft_count,
  (SELECT COUNT(*) FROM categories) AS category_count,
  (SELECT COUNT(*) FROM tags) AS tag_count,
  (SELECT COUNT(*) FROM comments) AS comment_count,
  (SELECT COUNT(*) FROM moments) AS moment_count,
  (SELECT COUNT(*) FROM friend_links) AS friend_link_count,
  (SELECT COUNT(*) FROM projects) AS project_count,
  (SELECT view_count FROM site_settings WHERE id = 1) AS view_count
`

type AdminStatsRow struct {
	PublishedCount  int64
	DraftCount      int64
	CategoryCount   int64
	TagCount        int64
	CommentCount    int64
	MomentCount     int64
	FriendLinkCount int64
	ProjectCount    int64
	ViewCount       uint64
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRowContext(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(
		&i.PublishedCount,
		&i.DraftCount,
		&i.CategoryCount,
		&i.TagCount,
		&i.CommentCount,
		&i.MomentCount,
		&i.FriendLinkCount,
		&i.ProjectCount,
		&i.ViewCount,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO categories (name) VALUES (?)
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory, name)
}

const createChangelog = `-- name: CreateChangelog :execresult
INSERT INTO changelogs (items, logged_at) VALUES (?, ?)
`

type CreateChangelogParams struct {
	Items    json.RawMessage
	LoggedAt time.Time
}

func (q *Queries) CreateChangelog(ctx context.Context, arg CreateChangelogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChangelog, arg.Items, arg.LoggedAt)
}

const createFriendLink = `-- name: CreateFriendLink :execresult
INSERT INTO friend_links (name, url, avatar, description) VALUES (?, ?, ?, ?)
`

type CreateFriendLinkParams struct {
	Name        string
	Url         string
	Avatar      string
	Description string
}

func (q *Queries) CreateFriendLink(ctx context.Context, arg CreateFriendLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFriendLink,
		arg.Name,
		arg.Url,
		arg.Avatar,
		arg.Description,
	)
}

const createMoment = `-- name: CreateMoment :execresult
INSERT INTO moments (content, images, created_at) VALUES (?, ?, ?)
`

type CreateMomentParams struct {
	Content   string
	Images    json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) CreateMoment(ctx context.Context, arg CreateMomentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMoment, arg.Content, arg.Images, arg.CreatedAt)
}

const createProject = `-- name: CreateProject :execresult
INSERT INTO projects (name, description, cover, url, sort_order) VALUES (?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	Name        string
	Description string
	Cover       string
	Url         string
	SortOrder   int32
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Cover,
		arg.Url,
		arg.SortOrder,
	)
}

const createTag = `-- name: CreateTag :execresult
INSERT INTO tags (name) VALUES (?)
`

func (q *Queries) CreateTag(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTag, name)
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChangelog = `-- name: DeleteChangelog :execrows
DELETE FROM changelogs WHERE id = ?
`

func (q *Queries) DeleteChangelog(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChangelog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFriendLink = `-- name: DeleteFriendLink :execrows
DELETE FROM friend_links WHERE id = ?
`

func (q *Queries) DeleteFriendLink(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFriendLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMoment = `-- name: DeleteMoment :execrows
DELETE FROM moments WHERE id = ?
`

func (q *Queries) DeleteMoment(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMoment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameCategory = `-- name: RenameCategory :execrows
UPDATE categories SET name = ? WHERE id = ?
`

type RenameCategoryParams struct {
	Name string
	ID   uint64
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameTag = `-- name: RenameTag :execrows
UPDATE tags SET name = ? WHERE id = ?
`

type RenameTagParams struct {
	Name string
	ID   uint64
}

func (q *Queries) RenameTag(ctx context.Context, arg RenameTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameTag, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChangelog = `-- name: UpdateChangelog :execrows
UPDATE changelogs SET items = ?, logged_at = ? WHERE id = ?
`

type UpdateChangelogParams struct {
	Items    json.RawMessage
	LoggedAt time.Time
	ID       uint64
}

func (q *Queries) UpdateChangelog(ctx context.Context, arg UpdateChangelogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChangelog, arg.Items, arg.LoggedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFriendLink = `-- name: UpdateFriendLink :execrows
UPDATE friend_links SET name = ?, url = ?, avatar = ?, description = ? WHERE id = ?
`

type UpdateFriendLinkParams struct {
	Name        string
	Url         string
	Avatar      string
	Description string
	ID          uint64
}

func (q *Queries) UpdateFriendLink(ctx context.Context, arg UpdateFriendLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFriendLink,
		arg.Name,
		arg.Url,
		arg.Avatar,
		arg.Description,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMoment = `-- name: UpdateMoment :execrows
UPDATE moments SET content = ?, images = ?, created_at = ? WHERE id = ?
`

type UpdateMomentParams struct {
	Content   string
	Images    json.RawMessage
	CreatedAt time.Time
	ID        uint64
}

func (q *Queries) UpdateMoment(ctx context.Context, arg UpdateMomentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMoment,
		arg.Content,
		arg.Images,
		arg.CreatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePage = `-- name: UpdatePage :execrows
UPDATE pages SET content = ? WHERE page_key = ?
`

type UpdatePageParams struct {
	Content string
	PageKey PagesPageKey
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePage, arg.Content, arg.PageKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects SET name = ?, description = ?, cover = ?, url = ?, sort_order = ? WHERE id = ?
`

type UpdateProjectParams struct {
	Name        string
	Description string
	Cover       string
	Url         string
	SortOrder   int32
	ID          uint64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Cover,
		arg.Url,
		arg.SortOrder,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
