// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT COUNT(*)
FROM articles a
LEFT JOIN categories c ON c.id = a.category_id
WHERE a.status = 'published'
  AND (? IS NULL OR a.title LIKE ?)
  AND (? IS NULL OR c.name = ?)
  AND (? IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at JOIN tags t ON t.id = at.tag_id
        WHERE at.article_id = a.id AND t.name = ?))
`

type CountPublishedArticlesParams struct {
	Keyword  sql.NullString
	Category sql.NullString
	Tag      sql.NullString
}

func (q *Queries) CountPublishedArticles(ctx context.Context, arg CountPublishedArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedArticles,
		arg.Keyword,
		arg.Keyword,
		arg.Category,
		arg.Category,
		arg.Tag,
		arg.Tag,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublishedArticle = `-- name: GetPublishedArticle :one
SELECT a.id, a.title, a.content, a.published_at, a.updated_at,
       a.category_id, c.name AS category_name
FROM articles a
LEFT JOIN categories c ON c.id = a.category_id
WHERE a.id = ? AND a.status = 'published'
`

type GetPublishedArticleRow struct {
	ID           uint64
	Title        string
	Content      string
	PublishedAt  time.Time
	UpdatedAt    time.Time
	CategoryID   sql.NullInt64
	CategoryName sql.NullString
}

func (q *Queries) GetPublishedArticle(ctx context.Context, id uint64) (GetPublishedArticleRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedArticle, id)
	var i GetPublishedArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
	)
	return i, err
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT a.id, a.title, a.content, a.published_at, a.updated_at,
       a.category_id, c.name AS category_name
FROM articles a
LEFT JOIN categories c ON c.id = a.category_id
WHERE a.status = 'published'
  AND (? IS NULL OR a.title LIKE ?)
  AND (? IS NULL OR c.name = ?)
  AND (? IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at JOIN tags t ON t.id = at.tag_id
        WHERE at.article_id = a.id AND t.name = ?))
ORDER BY a.published_at DESC, a.id DESC
LIMIT ? OFFSET ?
`

type ListPublishedArticlesParams struct {
	Keyword  sql.NullString
	Category sql.NullString
	Tag      sql.NullString
	Limit    int32
	Offset   int32
}

type ListPublishedArticlesRow struct {
	ID           uint64
	Title        string
	Content      string
	PublishedAt  time.Time
	UpdatedAt    time.Time
	CategoryID   sql.NullInt64
	CategoryName sql.NullString
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticles,
		arg.Keyword,
		arg.Keyword,
		arg.Category,
		arg.Category,
		arg.Tag,
		arg.Tag,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesRow{}
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForArticles = `-- name: ListTagsForArticles :many
SELECT at.article_id, t.id, t.name
FROM article_tags at
JOIN tags t ON t.id = at.tag_id
WHERE at.article_id IN (/*SLICE:article_ids*/?)
ORDER BY t.name
`

type ListTagsForArticlesRow struct {
	ArticleID uint64
	ID        uint64
	Name      string
}

func (q *Queries) ListTagsForArticles(ctx context.Context, articleIds []uint64) ([]ListTagsForArticlesRow, error) {
	query := listTagsForArticles
	var queryParams []interface{}
	if len(articleIds) > 0 {
		for _, v := range articleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:article_ids*/?", strings.Repeat(",?", len(articleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:article_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForArticlesRow{}
	for rows.Next() {
		var i ListTagsForArticlesRow
		if err := rows.Scan(&i.ArticleID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
