// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countTopLevelComments = `-- name: CountTopLevelComments :one
SELECT COUNT(*) FROM comments
WHERE article_id <=> ? AND parent_id IS NULL
`

func (q *Queries) CountTopLevelComments(ctx context.Context, articleID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTopLevelComments, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :execresult
INSERT INTO comments (article_id, parent_id, nickname, email, website, avatar, content, is_admin, ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Email     string
	Website   string
	Avatar    string
	Content   string
	IsAdmin   bool
	Ip        string
	UserAgent string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createComment,
		arg.ArticleID,
		arg.ParentID,
		arg.Nickname,
		arg.Email,
		arg.Website,
		arg.Avatar,
		arg.Content,
		arg.IsAdmin,
		arg.Ip,
		arg.UserAgent,
	)
}

const getArticleRef = `-- name: GetArticleRef :one
SELECT id, title FROM articles WHERE id = ?
`

type GetArticleRefRow struct {
	ID    uint64
	Title string
}

func (q *Queries) GetArticleRef(ctx context.Context, id uint64) (GetArticleRefRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleRef, id)
	var i GetArticleRefRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, article_id, parent_id, nickname, email, content, is_admin
FROM comments WHERE id = ?
`

type GetCommentRow struct {
	ID        uint64
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Email     string
	Content   string
	IsAdmin   bool
}

func (q *Queries) GetComment(ctx context.Context, id uint64) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.ParentID,
		&i.Nickname,
		&i.Email,
		&i.Content,
		&i.IsAdmin,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, article_id, parent_id, nickname, website, avatar, content, is_admin, created_at
FROM comments WHERE id = ?
`

type GetCommentByIDRow struct {
	ID        uint64
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Website   string
	Avatar    string
	Content   string
	IsAdmin   bool
	CreatedAt time.Time
}

func (q *Queries) GetCommentByID(ctx context.Context, id uint64) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.ParentID,
		&i.Nickname,
		&i.Website,
		&i.Avatar,
		&i.Content,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishedArticleRef = `-- name: GetPublishedArticleRef :one
SELECT id, title FROM articles WHERE id = ? AND status = 'published'
`

type GetPublishedArticleRefRow struct {
	ID    uint64
	Title string
}

func (q *Queries) GetPublishedArticleRef(ctx context.Context, id uint64) (GetPublishedArticleRefRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedArticleRef, id)
	var i GetPublishedArticleRefRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const listRepliesForParents = `-- name: ListRepliesForParents :many
SELECT id, article_id, parent_id, nickname, website, avatar, content, is_admin, created_at
FROM comments
WHERE parent_id IN (/*SLICE:parent_ids*/?)
ORDER BY created_at ASC, id ASC
`

type ListRepliesForParentsRow struct {
	ID        uint64
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Website   string
	Avatar    string
	Content   string
	IsAdmin   bool
	CreatedAt time.Time
}

func (q *Queries) ListRepliesForParents(ctx context.Context, parentIds []sql.NullInt64) ([]ListRepliesForParentsRow, error) {
	query := listRepliesForParents
	var queryParams []interface{}
	if len(parentIds) > 0 {
		for _, v := range parentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", strings.Repeat(",?", len(parentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepliesForParentsRow{}
	for rows.Next() {
		var i ListRepliesForParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ParentID,
			&i.Nickname,
			&i.Website,
			&i.Avatar,
			&i.Content,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelComments = `-- name: ListTopLevelComments :many
SELECT id, article_id, parent_id, nickname, website, avatar, content, is_admin, created_at
FROM comments
WHERE article_id <=> ? AND parent_id IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListTopLevelCommentsParams struct {
	ArticleID sql.NullInt64
	Limit     int32
	Offset    int32
}

type ListTopLevelCommentsRow struct {
	ID        uint64
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Website   string
	Avatar    string
	Content   string
	IsAdmin   bool
	CreatedAt time.Time
}

func (q *Queries) ListTopLevelComments(ctx context.Context, arg ListTopLevelCommentsParams) ([]ListTopLevelCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelComments, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopLevelCommentsRow{}
	for rows.Next() {
		var i ListTopLevelCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ParentID,
			&i.Nickname,
			&i.Website,
			&i.Avatar,
			&i.Content,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
