// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"
	"encoding/json"
	"time"
)

const countMoments = `-- name: CountMoments :one
SELECT COUNT(*) FROM moments
`

func (q *Queries) CountMoments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMoments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPage = `-- name: GetPage :one
SELECT page_key, content, updated_at FROM pages WHERE page_key = ?
`

func (q *Queries) GetPage(ctx context.Context, pageKey PagesPageKey) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, pageKey)
	var i Page
	err := row.Scan(&i.PageKey, &i.Content, &i.UpdatedAt)
	return i, err
}

const listChangelogs = `-- name: ListChangelogs :many
SELECT id, items, logged_at FROM changelogs
ORDER BY logged_at DESC, id DESC
`

type ListChangelogsRow struct {
	ID       uint64
	Items    json.RawMessage
	LoggedAt time.Time
}

func (q *Queries) ListChangelogs(ctx context.Context) ([]ListChangelogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangelogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangelogsRow{}
	for rows.Next() {
		var i ListChangelogsRow
		if err := rows.Scan(&i.ID, &i.Items, &i.LoggedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendLinks = `-- name: ListFriendLinks :many
SELECT id, name, url, avatar, description, created_at FROM friend_links
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListFriendLinks(ctx context.Context) ([]FriendLink, error) {
	rows, err := q.db.QueryContext(ctx, listFriendLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FriendLink{}
	for rows.Next() {
		var i FriendLink
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Avatar,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoments = `-- name: ListMoments :many
SELECT id, content, images, created_at FROM moments
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListMomentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMoments(ctx context.Context, arg ListMomentsParams) ([]Moment, error) {
	rows, err := q.db.QueryContext(ctx, listMoments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Moment{}
	for rows.Next() {
		var i Moment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Images,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
