// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ArticlesStatus string

const (
	ArticlesStatusDraft     ArticlesStatus = "draft"
	ArticlesStatusPublished ArticlesStatus = "published"
)

func (e *ArticlesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArticlesStatus(s)
	case string:
		*e = ArticlesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArticlesStatus: %T", src)
	}
	return nil
}

type NullArticlesStatus struct {
	ArticlesStatus ArticlesStatus
	Valid          bool // Valid is true if ArticlesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArticlesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArticlesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArticlesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArticlesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArticlesStatus), nil
}

type PagesPageKey string

const (
	PagesPageKeyAboutSite PagesPageKey = "about_site"
	PagesPageKeyAboutMe   PagesPageKey = "about_me"
)

func (e *PagesPageKey) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PagesPageKey(s)
	case string:
		*e = PagesPageKey(s)
	default:
		return fmt.Errorf("unsupported scan type for PagesPageKey: %T", src)
	}
	return nil
}

type NullPagesPageKey struct {
	PagesPageKey PagesPageKey
	Valid        bool // Valid is true if PagesPageKey is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPagesPageKey) Scan(value interface{}) error {
	if value == nil {
		ns.PagesPageKey, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PagesPageKey.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPagesPageKey) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PagesPageKey), nil
}

type UsersRole string

const (
	UsersRoleAdmin UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole
	Valid     bool // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type Article struct {
	ID          uint64
	Title       string
	Content     string
	CategoryID  sql.NullInt64
	Status      ArticlesStatus
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ArticleTag struct {
	ArticleID uint64
	TagID     uint64
}

type Category struct {
	ID        uint64
	Name      string
	CreatedAt time.Time
}

type Changelog struct {
	ID        uint64
	Items     json.RawMessage
	LoggedAt  time.Time
	CreatedAt time.Time
}

type Comment struct {
	ID        uint64
	ArticleID sql.NullInt64
	ParentID  sql.NullInt64
	Nickname  string
	Email     string
	Website   string
	Avatar    string
	Content   string
	IsAdmin   bool
	Ip        string
	UserAgent string
	CreatedAt time.Time
}

type FriendLink struct {
	ID          uint64
	Name        string
	Url         string
	Avatar      string
	Description string
	CreatedAt   time.Time
}

type Moment struct {
	ID        uint64
	Content   string
	Images    json.RawMessage
	CreatedAt time.Time
}

type Page struct {
	PageKey   PagesPageKey
	Content   string
	UpdatedAt time.Time
}

type SiteSetting struct {
	ID        uint8
	Notice    string
	ViewCount uint64
	UpdatedAt time.Time
}

type Tag struct {
	ID        uint64
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID           uint64
	Email        string
	PasswordHash string
	Nickname     string
	Avatar       string
	Website      string
	Role         UsersRole
	CreatedAt    time.Time
	TokenVersion uint32
}
