// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddArticleTag(ctx context.Context, arg AddArticleTagParams) error
	AdminCountArticles(ctx context.Context, arg AdminCountArticlesParams) (int64, error)
	AdminCountComments(ctx context.Context) (int64, error)
	AdminGetArticle(ctx context.Context, id uint64) (AdminGetArticleRow, error)
	AdminListArticles(ctx context.Context, arg AdminListArticlesParams) ([]AdminListArticlesRow, error)
	AdminListComments(ctx context.Context, arg AdminListCommentsParams) ([]AdminListCommentsRow, error)
	AdminStats(ctx context.Context) (AdminStatsRow, error)
	ArticleExists(ctx context.Context, id uint64) (int64, error)
	CountMoments(ctx context.Context) (int64, error)
	CountPublishedArticles(ctx context.Context, arg CountPublishedArticlesParams) (int64, error)
	CountTopLevelComments(ctx context.Context, articleID sql.NullInt64) (int64, error)
	CountUncategorizedPublished(ctx context.Context) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error)
	CreateCategory(ctx context.Context, name string) (sql.Result, error)
	CreateChangelog(ctx context.Context, arg CreateChangelogParams) (sql.Result, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (sql.Result, error)
	CreateFriendLink(ctx context.Context, arg CreateFriendLinkParams) (sql.Result, error)
	CreateMoment(ctx context.Context, arg CreateMomentParams) (sql.Result, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	CreateTag(ctx context.Context, name string) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteArticle(ctx context.Context, id uint64) (int64, error)
	DeleteArticleTags(ctx context.Context, articleID uint64) error
	DeleteCategory(ctx context.Context, id uint64) (int64, error)
	DeleteChangelog(ctx context.Context, id uint64) (int64, error)
	DeleteComment(ctx context.Context, id uint64) (int64, error)
	DeleteFriendLink(ctx context.Context, id uint64) (int64, error)
	DeleteMoment(ctx context.Context, id uint64) (int64, error)
	DeleteProject(ctx context.Context, id uint64) (int64, error)
	DeleteTag(ctx context.Context, id uint64) (int64, error)
	GetArticleRef(ctx context.Context, id uint64) (GetArticleRefRow, error)
	GetComment(ctx context.Context, id uint64) (GetCommentRow, error)
	GetCommentByID(ctx context.Context, id uint64) (GetCommentByIDRow, error)
	GetPage(ctx context.Context, pageKey PagesPageKey) (Page, error)
	GetPublishedArticle(ctx context.Context, id uint64) (GetPublishedArticleRow, error)
	GetPublishedArticleRef(ctx context.Context, id uint64) (GetPublishedArticleRefRow, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetSiteStats(ctx context.Context) (GetSiteStatsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	// LAST_INSERT_ID(expr) makes the new value available via Result.LastInsertId without a second query.
	IncrementViewCount(ctx context.Context) (sql.Result, error)
	ListCategoriesWithCount(ctx context.Context) ([]ListCategoriesWithCountRow, error)
	ListChangelogs(ctx context.Context) ([]ListChangelogsRow, error)
	ListFriendLinks(ctx context.Context) ([]FriendLink, error)
	ListMoments(ctx context.Context, arg ListMomentsParams) ([]Moment, error)
	ListProjects(ctx context.Context) ([]ListProjectsRow, error)
	ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error)
	ListRepliesForParents(ctx context.Context, parentIds []sql.NullInt64) ([]ListRepliesForParentsRow, error)
	ListTagsForArticles(ctx context.Context, articleIds []uint64) ([]ListTagsForArticlesRow, error)
	ListTagsWithCount(ctx context.Context) ([]ListTagsWithCountRow, error)
	ListTopLevelComments(ctx context.Context, arg ListTopLevelCommentsParams) ([]ListTopLevelCommentsRow, error)
	RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error)
	RenameTag(ctx context.Context, arg RenameTagParams) (int64, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (int64, error)
	UpdateChangelog(ctx context.Context, arg UpdateChangelogParams) (int64, error)
	UpdateFriendLink(ctx context.Context, arg UpdateFriendLinkParams) (int64, error)
	UpdateMoment(ctx context.Context, arg UpdateMomentParams) (int64, error)
	UpdateNotice(ctx context.Context, notice string) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
