// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package store

import (
	"context"
	"database/sql"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, notice, view_count, updated_at FROM site_settings WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.Notice,
		&i.ViewCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteStats = `-- name: GetSiteStats :one
SELECT
  (SELECT COUNT(*) FROM articles WHERE status = 'published') AS article_count,
  (SELECT COUNT(*) FROM categories) AS category_count,
  (SELECT COUNT(*) FROM tags) AS tag_count
`

type GetSiteStatsRow struct {
	ArticleCount  int64
	CategoryCount int64
	TagCount      int64
}

func (q *Queries) GetSiteStats(ctx context.Context) (GetSiteStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteStats)
	var i GetSiteStatsRow
	err := row.Scan(&i.ArticleCount, &i.CategoryCount, &i.TagCount)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :execresult
UPDATE site_settings SET view_count = LAST_INSERT_ID(view_count + 1) WHERE id = 1
`

// LAST_INSERT_ID(expr) makes the new value available via Result.LastInsertId without a second query.
func (q *Queries) IncrementViewCount(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, incrementViewCount)
}

const updateNotice = `-- name: UpdateNotice :exec
UPDATE site_settings SET notice = ? WHERE id = 1
`

func (q *Queries) UpdateNotice(ctx context.Context, notice string) error {
	_, err := q.db.ExecContext(ctx, updateNotice, notice)
	return err
}
