// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package store

import (
	"context"
	"time"
)

const countUncategorizedPublished = `-- name: CountUncategorizedPublished :one
SELECT COUNT(*) FROM articles WHERE status = 'published' AND category_id IS NULL
`

func (q *Queries) CountUncategorizedPublished(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUncategorizedPublished)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategoriesWithCount = `-- name: ListCategoriesWithCount :many
SELECT c.id, c.name, c.created_at,
       CAST(COUNT(a.id) AS SIGNED) AS article_count
FROM categories c
LEFT JOIN articles a ON a.category_id = c.id AND a.status = 'published'
GROUP BY c.id, c.name, c.created_at
ORDER BY c.created_at DESC, c.id DESC
`

type ListCategoriesWithCountRow struct {
	ID           uint64
	Name         string
	CreatedAt    time.Time
	ArticleCount int64
}

func (q *Queries) ListCategoriesWithCount(ctx context.Context) ([]ListCategoriesWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithCountRow{}
	for rows.Next() {
		var i ListCategoriesWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCount = `-- name: ListTagsWithCount :many
SELECT t.id, t.name, t.created_at,
       CAST(COUNT(a.id) AS SIGNED) AS article_count
FROM tags t
LEFT JOIN article_tags at ON at.tag_id = t.id
LEFT JOIN articles a ON a.id = at.article_id AND a.status = 'published'
GROUP BY t.id, t.name, t.created_at
ORDER BY t.created_at DESC, t.id DESC
`

type ListTagsWithCountRow struct {
	ID           uint64
	Name         string
	CreatedAt    time.Time
	ArticleCount int64
}

func (q *Queries) ListTagsWithCount(ctx context.Context) ([]ListTagsWithCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithCountRow{}
	for rows.Next() {
		var i ListTagsWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
