// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, password_hash, nickname, avatar, website, role)
VALUES (?, ?, ?, ?, ?, 'admin')
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Nickname     string
	Avatar       string
	Website      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Nickname,
		arg.Avatar,
		arg.Website,
	)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, nickname, avatar, website, role, created_at, token_version FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Website,
		&i.Role,
		&i.CreatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, nickname, avatar, website, role, created_at, token_version FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Avatar,
		&i.Website,
		&i.Role,
		&i.CreatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = ?, token_version = token_version + 1 WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           uint64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE users SET nickname = ?, avatar = ?, website = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Nickname string
	Avatar   string
	Website  string
	ID       uint64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.Nickname,
		arg.Avatar,
		arg.Website,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
